In [2]:
import pandas as pd
import requests

注释

In [3]:
df = pd.read_excel('E:\\data science\\Data-sheet-STUDENTS.xlsx',header = 2, index_col = 0)

In [4]:
df['Country (according to CN Gov):']

1                            Afghanistan
2                                Albania
3                                Armenia
4                             Azerbaijan
5                                Bahrain
6                             Bangladesh
7                                Belarus
8                                 Bhutan
9                 Bosnia and Herzegovina
10                                Brunei
11                              Bulgaria
12                              Cambodia
13                                 China
14                               Croatia
15                        Czech Republic
16                            East Timor
17                                 Egypt
18                               Estonia
19                      France (Not BRI)
20                               Georgia
21                     Germany (not BRI)
22                               Hungary
23                                 India
24                             Indonesia
25                                  Iran
26                                  Iraq
27                                Israel
28                                Jordan
29                            Kazakhstan
30                                Kuwait
                     ...
39                               Moldova
40                              Mongolia
41                            Montenegro
42                               Myanmar
43                                 Nepal
44                                  Oman
45                              Pakistan
46                           Philippines
47                                Poland
48                                 Qatar
49                               Romania
50                                Russia
51                          Saudi Arabia
52                                Serbia
53                             Singapore
54                              Slovakia
55                              Slovenia
56                             Sri Lanka
57                                 Syria
58                            Tajikistan
59                             Thailiand
60              The United Arab Emirates
61                                Turkey
62                          Turkmenistan
63              United Kingdom (Not BRI)
64    United States of America (Not BRI)
65                               Ukraine
66                            Uzbekistan
67                               Vietnam
68                                 Yemen
Name: Country (according to CN Gov):, Length: 68, dtype: object

In [5]:
df.describe()

,HF Index of Economic Freedom (Scale: 1-100),Heritage Foundation Index of Economic Freedom (Global Ranking),Bertelsmann Transformation index (BTI),Bertelsmann Transformation index (BTI) - Ranking,IMF WB Customs and other import duties (% of tax revenue) 2016,WB IMF Non-performing loans to total gross loans ratio (%),UIC Rail freight (mn ton x km travelled),ICAO air freight (mn ton x km travelled),"WB Household final consumption expenditure, PPP bn USD",WB UNESCO R&D Expenditure % of GDP,...,BRI Percentage of Urban Population in Total Population,WB Cost of Starting a Business,WB Ease of Doing Business Index (1 = most business-friendly regulations),WB Logistics Performance Index (LPI) (range: 1-5),IFDI Net Inflows (% of GDP),ED National Electric Power Consumption TwH,"WHO Current Health Expenditure p.c., PPP USD",WB Research Expenditure % of GDP,WIPO Trademark applications,WIPO Patent Applications
count,6.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.00000,0.0,...,2.000000,2.000000,0.0,3.000000,2.000000,1.0,2.000000,2.000000,2.000000,2.000000
mean,53.533333,61.500000,5.000000,78.000000,8.750500,0.018085,47.535500,631.256500,222.20150,NaN,...,0.477140,28.350000,NaN,3.333333,7.225000,149.0,636.752500,636.752500,9.854500,0.554500
std,15.459840,55.861436,1.414214,35.355339,9.948285,0.003726,62.882299,891.492653,261.02069,NaN,...,0.381710,32.456201,NaN,0.815925,5.941111,NaN,604.060817,604.060817,12.264767,0.784181
min,34.000000,22.000000,4.000000,53.000000,1.716000,0.015450,3.071000,0.876000,37.63200,NaN,...,0.207230,5.400000,NaN,2.580000,3.024000,149.0,209.617000,209.617000,1.182000,0.000000
25%,41.500000,41.750000,4.500000,65.500000,5.233250,0.016768,25.303250,316.066250,129.91675,NaN,...,0.342185,16.875000,NaN,2.900000,5.124500,149.0,423.184750,423.184750,5.518250,0.277250
50%,56.850000,61.500000,5.000000,78.000000,8.750500,0.018085,47.535500,631.256500,222.20150,NaN,...,0.477140,28.350000,NaN,3.220000,7.225000,149.0,636.752500,636.752500,9.854500,0.554500
75%,61.175000,81.250000,5.500000,90.500000,12.267750,0.019402,69.767750,946.446750,314.48625,NaN,...,0.612095,39.825000,NaN,3.710000,9.325500,149.0,850.320250,850.320250,14.190750,0.831750
max,74.500000,101.000000,6.000000,103.000000,15.785000,0.020720,92.000000,1261.637000,406.77100,NaN,...,0.747050,51.300000,NaN,4.200000,11.426000,149.0,1063.888000,1063.888000,18.527000,1.109000

In [6]:
iso_codes = {}

In [11]:
for index, name in df['Country (according to CN Gov):'].items():
    if name in iso_codes:
        continue
    
    cleaned_name = name.split('(')[0].strip()
    if cleaned_name == 'Thailiand':
        cleaned_name = 'Thailand'
    elif cleaned_name == 'The United Arab Emirates':
        cleaned_name = 'United Arab Emirates'
    
    
    url = 'https://restcountries.eu/rest/v2/name/' + cleaned_name
    r = requests.get(url)
    if r.status_code == 200:
        data = r.json()
        country_code = data[0]['alpha3Code']
        iso_codes[name] = country_code
    else:
        print('[ERROR] we cannot get the data')
        print(name)

In [8]:
df['isocode'] = df['Country (according to CN Gov):'].apply(lambda x: iso_codes[x])

In [9]:
df[['isocode','Country (according to CN Gov):']]

   isocode      Country (according to CN Gov):
1      AFG                         Afghanistan
2      ALB                             Albania
3      ARM                             Armenia
4      AZE                          Azerbaijan
5      BHR                             Bahrain
6      BGD                          Bangladesh
7      BLR                             Belarus
8      BTN                              Bhutan
9      BIH              Bosnia and Herzegovina
10     BRN                              Brunei
11     BGR                            Bulgaria
12     KHM                            Cambodia
13     CHN                               China
14     HRV                             Croatia
15     CZE                      Czech Republic
16     TLS                          East Timor
17     EGY                               Egypt
18     EST                             Estonia
19     FRA                    France (Not BRI)
20     GEO                             Georgia
21     DEU                   Germany (not BRI)
22     HUN                             Hungary
23     IOT                               India
24     IDN                           Indonesia
25     IRN                                Iran
26     IRQ                                Iraq
27     ISR                              Israel
28     JOR                              Jordan
29     KAZ                          Kazakhstan
30     KWT                              Kuwait
..     ...                                 ...
39     MDA                             Moldova
40     MNG                            Mongolia
41     MNE                          Montenegro
42     MMR                             Myanmar
43     NPL                               Nepal
44     OMN                                Oman
45     PAK                            Pakistan
46     PHL                         Philippines
47     POL                              Poland
48     QAT                               Qatar
49     ROU                             Romania
50     RUS                              Russia
51     SAU                        Saudi Arabia
52     SRB                              Serbia
53     SGP                           Singapore
54     SVK                            Slovakia
55     SVN                            Slovenia
56     LKA                           Sri Lanka
57     SYR                               Syria
58     TJK                          Tajikistan
59     THA                           Thailiand
60     ARE            The United Arab Emirates
61     TUR                              Turkey
62     TKM                        Turkmenistan
63     GBR            United Kingdom (Not BRI)
64     USA  United States of America (Not BRI)
65     UKR                             Ukraine
66     UZB                          Uzbekistan
67     VNM                             Vietnam
68     YEM                               Yemen

[68 rows x 2 columns]